### ISSUE TITLE
Bug to handle path (I think)

### ISSUE THREAD

**Issue by RodrigoKazuma** [RobotsOnDrugs/BDSM#1]
Hello there,

I'm trying to use the executable of your BDSM, but I get this error.

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\HS2mods\Sideloader Modpack - Uncensor Selector'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.EnumerateFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at BDSM.BDSM.Main() in C:\Users\iamtheclaw\source\repos\BDSM\BDSM.cs:line 121
```

**Comment by RobotsOnDrugs** [comment]
Paste your UserConfiguration.yaml and a listing of the contents inside E:\HS2mods. It may just be a case of it not making the directory for you, or it could be something with what you've configured.

**Comment by RodrigoKazuma** [comment]
I think I found the reason for 1 problem:
In the UserConfiguration.yaml I forget to put the last '\:
```GamePath: E:\HS2```
I should put;
```GamePath: E:\HS2\```

But I still can't understand this C:\Users\iamtheclaw\source\repos\BDSM\BDSM.cs

I don't have this user on my computer.

**Comment by RobotsOnDrugs** [comment]
> I think I found the reason for 1 problem: In the UserConfiguration.yaml I forget to put the last ': `GamePath: E:\HS2` I should put; `GamePath: E:\HS2\`

I thought I had that taken care of, but apparently not. It shouldn't matter whether there's a trailing \ or not, so I will fix that.

> But I still can't understand this C:\Users\iamtheclaw\source\repos\BDSM\BDSM.cs
> 
> I don't have this user on my computer.

It's for showing where in the code it happened. Unless you compiled it yourself, you don't need to worry about it.

**Comment by RodrigoKazuma** [comment]
Everything works fine now.

In any case, thanks.
