### ISSUE TITLE
Handle connection issues during scanning phase

### ISSUE THREAD

**Issue by ssj4maiko** [RobotsOnDrugs/BDSM#6]
Not sure if it's related, I had modified the yaml (I didn't think the GamePath was supposed to be the only change) a bit more, reflecting what I could see from `sideload.betterrepack.com`, which means that it got things wrong, and deleted all my files.

After fixing the yaml back to how it was, just with my gamepath, it seems that things run better, but then I got this, you can see an 5 minutes wait on the timestamps
```
[2022-12-16 21:11:06.3093] Info: Configuration loaded.
[2022-12-16 21:11:06.3319] Info: Scanning the server.
[2022-12-16 21:17:24.1686] Error: Could not scan the server. Failed scan tasks had the following errors:
[2022-12-16 21:17:24.1686] Error: Failed to get the EPSV port from: Directory send OK.
[2022-12-16 21:17:24.1805] Error:    at FluentFTP.Client.BaseClient.BaseFtpClient.GetEnhancedPassivePort(FtpReply reply, String& host, Int32& port)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   at BDSM.FTPFunctions.GetFilesOnServer(ConcurrentBag`1& pathmaps, RepoConnectionInfo repoinfo) in C:\Users\iamtheclaw\source\repos\BDSM\FTPFunctions.cs:line 51
   at BDSM.BDSM.<>c__DisplayClass19_0.<Main>b__1() in C:\Users\iamtheclaw\source\repos\BDSM\BDSM.cs:line 144
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2022-12-16 21:17:24.1805] Error: Please file a bug report and provide this information. https://github.com/RobotsOnDrugs/BDSM/issues
```

One change though, I had lowered the number of connections to 2. When I added 5 back, it's working.

**Comment by RobotsOnDrugs** [comment]
> Not sure if it's related, I had modified the yaml (I didn't think the GamePath was supposed to be the only change) a bit more, reflecting what I could see from sideload.betterrepack.com, which means that it got things wrong, and deleted all my files.

If you're not sure what a setting is for, I highly recommend leaving it alone. I'm guessing you changed the root path to something other than `/AI/`. Stuff under `ConnectionInfo` is definitely stuff you don't want to touch unless you know what you're doing (and I'll probably rearrange configuration stuff into different files for v0.3).
Also, `PromptToContinue` is `true` by default for reasons like this. It should list all the files it would delete and then pause and wait for you to either cancel with Ctrl-C or continue with another key. If you kept that set to `true` and it did not prompt you before deleting files, please file another bug report and I'll look into why.

Proper documentation is still sorely lacking at this stage, and a guide to getting started is coming soon.

What it seems like to me is that it's a temporary hiccup with your connection to the server and BDSM doesn't handle it and just nopes out. I have not yet put in proper handling of some temporary connection issues, and will be implementing those very soon. In cases like this, it should probably just try again.

Are you able to reproduce this consistently with any configuration? If you have a configuration that induces issues like this more frequently, please paste it along with the error and any other relevant information.

**Comment by ssj4maiko** [comment]
The reason I changed is because I know that it's possible to download from this link `https://sideload.betterrepack.com/download/AISHS2/`, which is why, when I saw the name "example", I had understood that it was just giving an example, and I was the one supposed to find the real data, which is why I changed `/AI` to `/AISHS2`, which resulted in it.

In regards to PromptToContinue, yes, it was set to true, however, all I got was a huge wall of text that ended like this:
```
(...)
[2022-12-16 21:06:57.7978] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] bmary v1.0.zipmod
[2022-12-16 21:06:57.7978] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] asuka v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] aranea v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] anna v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] amsw v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] akira v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\[cunihinx] Ada_RE2R.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\cunihinx\Patreon.url
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\B17\[B17] HairModHS2_DX v1.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\B17\[B17] HairMod v1.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\Avidita01\[Avidita01] Skyrim Tanker Neisa v1.0.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\3dh9527\[3dh9527] NewMakerPoses.zipmod
[2022-12-16 21:06:57.8227] Info: Y:\Games\Honey Select 2 DX\mods\Sideloader Modpack - Exclusive HS2\[SCM] Ada Wong v2.0.zipmod
Press any key to continue or Ctrl-C to abort
```
Nothing about what it's going to do, nothing saying it's going to delete everything, or download these items (`I was updating after all, it's not like I know all mods that are installed`)

**So I would recommend printing a summary of actions at the end of the file list, counting how many items are being added/updated or deleted.**

A reminder, this was my first time running, so it's not like I have any idea how things run in the first place.

In cases like this, **I would also recommend, if nothing is found on server, close the process, I don't think there is any logical circumstance that anyone would want to delete everything of their files.**

And as I pointed out, after I increased the number of connections to 5, it worked, so now I'm downloading 200GB+ of files (I lost nothing personal, I also had commented the Userdata line because it doesn't exist on the link I knew of, which corroborated to my guess that all configuration was just for examples.

If it was something momentary, I guess I will know next time I try.

---------

I understand that the application is still in it's first steps, so I'm giving some User Experience tips to help avoiding future problems. :)

**Comment by RobotsOnDrugs** [comment]
> So I would recommend printing a summary of actions at the end of the file list, counting how many items are being added/updated or deleted.

Easily fixed, and will be pushed soon.

> In cases like this, I would also recommend, if nothing is found on server, close the process, I don't think there is any logical circumstance that anyone would want to delete everything of their files.

I've opened this as #7.

> I understand that the application is still in it's first steps, so I'm giving some User Experience tips to help avoiding future problems.

I appreciate it. You're always welcome to file more reports for rough edges like these.
